
-- Add show_in_directory flag to user_profiles
ALTER TABLE public.user_profiles
ADD COLUMN IF NOT EXISTS show_in_directory boolean NOT NULL DEFAULT false;

-- Set show_in_directory = true for all approved primary emails (case-insensitive)
UPDATE public.user_profiles
SET show_in_directory = true
WHERE LOWER(email) IN (
  -- Left column: existing network members
  'uel.migan@southbgroup.com',
  'andylower@adapcapital.com',
  'tadlam@agrifrontier.com',
  'lisa@atgsamata.com',
  'lelemba@africatrustgroup.com',
  'tawana@africa-growth.com',
  'andiac@gracamacheltrust.org',
  'invteam@altreecapital.com',
  'jchamberlain@altreecapital.com',
  'angela@angazacapital.com',
  'shiva@ankurcapital.com',
  'audrey@anza.holdings',
  'aor@aruwacapital.com',
  'josh@balloonventures.com',
  'rekia@barkafund.com',
  'shuyin@beaconfund.asia',
  'amel.saidane@betawaves.io',
  'rui.goncalves.oliveira@am.bfa.ao',
  'ndeye.thiaw@brightmorecapital.com',
  'victoria@gc.fund',
  'd.doumbia@comoecapital.com',
  'a.fofana@comoecapital.com',
  'micheal@cosefinvest.com',
  'alberto@co.org.mx',
  'tekiyor@nigeriasme.ng',
  'jacobus@growthcap.co.za',
  'geraldine@darenaventures.com',
  'thandeka@digitalafricaventures.com',
  'teluwo@fbx.ventures',
  'eddie.sembatya@findingxy.com',
  'selma@firstcircle.capital',
  'hema@five35.ventures',
  'tolulope@fluxiscapital.com',
  'steven@frontend.vc',
  'lmramba@gbfund.org',
  'teddy.onserio@habacapital.com',
  'wakiuru@hevafund.com',
  'josh@holocene.africa',
  'klakhani@invest2innovate.com',
  'ambar@ibtikarfund.com',
  'a.annan@impcapadv.com',
  'kim@inuacapital.com',
  'roeland@iungocapital.com',
  'july.andraous@jambaar-capital.com',
  'sewu@jazarift.vc',
  'vfraser@jengacapital.com',
  'hilina@kazanafund.com',
  'victor.ndiege@kcv.co.ke',
  'julia@lineacap.com',
  'idris.bello@loftyincltd.biz',
  'sejakekana@gmail.com',
  'mamokete@mamorcapital.com',
  'e.cotsoyannis@miarakap.com',
  'dayo@microtraction.com',
  'enyonam@mirepaadvisors.com',
  'enyonam@mirepacapital.com',
  'ani@mostfund.vc',
  'egla@msftventures.com',
  'is@neper.africa',
  'lsz@nordicimpactfunds.com',
  'aarthi.ramasubramanian@opensfund.eu',
  'klegesi@ortusafrica.com',
  'funmiadepoju@gmail.com',
  'rtugume@practitionerscp.com',
  'ldavis@renewcapital.com',
  'karthik@sangam.vc',
  'anne@sayuni.capital',
  'brendan@sechacapital.com',
  'p.koelbl@shequity.com',
  'imandela@shonacapital.co',
  'jzongo@sinergiburkina.com',
  'allert@mmfm-ltd.com',
  'sawadh@ssc.co.tz',
  'olivier.furdelle@terangacapital.com',
  'jaap-jan@truvalu-group.com',
  'shiluba@tshiamoimpact.com',
  'patrick.mutenda@gmail.com',
  'sov.leang@uberiscapital.com',
  'franziska@unconventional.capital',
  'chai@vakayi.com',
  'nneka@vestedworld.com',
  'stephengugu@viktoria.co.ke',
  'wilfred@villgroafrica.org',
  'e.arthur@wangaracapital.com',
  'martin@warioba.ventures',
  'nyeji@womencapital.co',
  'amaka@weavcapital.com',
  'edioh@wic-capital.net',
  -- Right column: current network members needing accounts
  'araptis@amplifica.capital',
  'aniko@atlanticaventures.com',
  'ha@climateresilience.fund',
  'nalin@climateseeds.fund',
  'amanda.kabagambe@betheladvisors.com',
  'renee@grounded.co.za',
  'janice@ivhuadvisors.com',
  'caitlin.wale@kinjani.com',
  'maike@socialinnovationacademy.org',
  'susanneroelofsen@gmail.com',
  'priya@theia-ventures.com',
  'biyayi@unicorngrowth.co',
  'ory@vkav.vc'
);

-- Also handle cases where email might have been stored with different casing
-- by checking the bfa primary
UPDATE public.user_profiles
SET show_in_directory = true
WHERE LOWER(email) LIKE '%@am.bfa.ao' AND show_in_directory = false;
